name: Build Polish Tablet Experience

on:
  push:
    branches:
      - main
      - dev

jobs:
  build_preview:
    name: Preview Build (Dev)
    if: ${{ github.ref == 'refs/heads/dev' }}
    type: build
    params:
      platform: android
      profile: preview

  build_production:
    name: Production Build (Main)
    if: ${{ github.ref == 'refs/heads/main' }}
    type: build
    params:
      platform: android
      profile: production